## MongoDB configuration
#spring.data.mongodb.host=mongodb://dterminetor53:w3Po3caEPKIskGXY@cluster0-shard-00-00.zcee7.mongodb.net:27017,cluster0-shard-00-01.zcee7.mongodb.net:27017,cluster0-shard-00-02.zcee7.mongodb.net:27017/Buizzment?ssl=true&replicaSet=atlas-101686-shard-0&authSource=admin&retryWrites=true&w=majority&appName=Cluster0
#mongodb://dterminetor53:w3Po3caEPKIskGXY@cluster0-shard-00-00.zcee7.mongodb.net:27017,cluster0-shard-00-01.zcee7.mongodb.net:27017,cluster0-shard-00-02.zcee7.mongodb.net:27017/?ssl=true&replicaSet=atlas-101686-shard-0&authSource=admin&retryWrites=true&w=majority&appName=Cluster0
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=buizzment
#mongodb+srv://sudhansugupta154:ew8ef1o1QYjiLEN4@cluster0.q1fvp.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
# MongoDB configuration
#spring.data.mongodb.uri=mongodb://localhost:27017/buizzment
# or with authentication:
 spring.data.mongodb.uri=mongodb://dterminetor53:w3Po3caEPKIskGXY@cluster0-shard-00-00.zcee7.mongodb.net:27017,cluster0-shard-00-01.zcee7.mongodb.net:27017,cluster0-shard-00-02.zcee7.mongodb.net:27017/Buizzment?ssl=true&replicaSet=atlas-101686-shard-0&authSource=admin&retryWrites=true&w=majority&appName=Cluster0
# Enable MongoDB logging for debugging
logging.level.org.springframework.data.mongodb=DEBUG

# JWT Configuration
# Replace with a strong secret key (at least 32 characters)
jwt.secret=ThisIsASuperStrongSecretKeyWithAtLeast32Characters123!
#jwt.secret=buizzmentSecretKey   // too short
jwt.expiration=86400000
# 24 hours in milliseconds


# Security
security.jwt.header=Authorization
security.jwt.prefix=Bearer